<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Labels: <?php echo $username; ?></title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css">
    </head>

    <body>

    <h1>Labels: <a href="https://github.com/<?php echo $username; ?>"><?php echo $username; ?></a></h1>

    <table class="table table-stripped">
        <thead>
        <tr>
            <th>Repository name</th>
            <th>Labels</th>
        </tr>
        </thead>
        <tbody>
        <?php
        foreach ($data as $repo => $labels) {
            echo '<tr>', PHP_EOL;
                echo "\t", '<td style="white-space: nowrap;"><a href="https://github.com/' . $username . '/' . $repo . '/labels">' . $repo . '</a></td>', PHP_EOL;
                echo "\t", '<td>', PHP_EOL;
                    foreach ($labels as $label => $color) {
                        echo "\t\t", '<span class="label" style="background-color:#' . $color . ';">' . $label . '</span>', PHP_EOL;
                    }
                echo "\t", '</td>', PHP_EOL;
            echo '</tr>', PHP_EOL;
        }
        ?>
        </tbody>
    </table>

    <footer>
        <p>Generated at: <i><?php echo date('r'); ?></i></p>
    </footer>

    </body>
</html>
